# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iconURL', models.FilePathField(max_length=300)),
                ('order', models.DecimalField(decimal_places=2, max_digits=2)),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
