# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0002_auto_20160601_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='iconURL',
            field=models.CharField(max_length=300),
        ),
    ]
