# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0004_auto_20160602_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='iconURL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
