# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0005_auto_20160602_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
