# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0009_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('characteristic', models.TextField()),
                ('jobTitle', models.CharField(max_length=200)),
                ('organizationName', models.CharField(max_length=200)),
                ('twitterName', models.CharField(max_length=200)),
                ('webSite', models.CharField(max_length=200)),
                ('avatarImageURL', models.CharField(max_length=200)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
