# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0011_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('imageURL', models.URLField()),
                ('detailURL', models.URLField()),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='avatarImageURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='iconURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
