# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0012_auto_20160605_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='detailURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='avatarImageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
