# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0013_auto_20160605_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('version', models.CharField(max_length=200)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('deleted', models.BooleanField()),
                ('experienceLevel', models.ManyToManyField(to='drupalcamp.Level')),
                ('speakers', models.ManyToManyField(to='drupalcamp.Speaker')),
                ('track', models.ManyToManyField(to='drupalcamp.Track')),
            ],
        ),
    ]
