# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0016_socialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
