# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0017_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imageURL', models.URLField(blank=True, null=True)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
