# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0019_auto_20160605_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
