# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0020_auto_20160605_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='description',
        ),
        migrations.AddField(
            model_name='bof',
            name='type',
            field=models.ManyToManyField(blank=True, to='drupalcamp.Type'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.ManyToManyField(blank=True, to='drupalcamp.Type'),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='type',
            field=models.ManyToManyField(blank=True, to='drupalcamp.Type'),
        ),
    ]
