# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0022_auto_20160607_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='type',
        ),
    ]
