# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0024_auto_20160607_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='experienceLevel',
        ),
        migrations.RemoveField(
            model_name='session',
            name='experienceLevel',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='experienceLevel',
        ),
    ]
