# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0026_auto_20160607_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='track',
        ),
        migrations.RemoveField(
            model_name='session',
            name='track',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='track',
        ),
    ]
