# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0027_auto_20160607_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='bof',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drupalcamp.Track'),
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drupalcamp.Track'),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drupalcamp.Track'),
        ),
    ]
