# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drupalcamp', '0028_auto_20160607_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bof',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bof',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='socialevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='bof',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bof',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
